import * as Yup from "yup";

export const SignupSchema = Yup.object().shape({
  companyName: Yup.string().min(3, "Too Short!").required("Required"),
  companyLogo: Yup.string().required("Required"),
  companyDesc: Yup.string()
    .min(10, "At least 10 characters")
    .required("Required"),
  jobDesc: Yup.string().min(10, "At least 10 characters").required("Required"),
  techStack: Yup.string().required("Required"),
  yearofExperience: Yup.string().required("Required"),
  salary: Yup.string().required("Required"),
  location: Yup.string().required("Required"),
  workTime: Yup.string().required("Required"),
  workMode: Yup.string().required("Required"),
});

export const UserLoginInitial = {
  companyName: "",
  companyLogo: "",
  companyDesc: "",
  jobDesc: "",
  techStack: "",
  yearofExperience: "",
  salary: "",
  location: "",
  workTime: "",
  workMode: "",
};

export const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const jobs = [
  {
    id: "J1",
    name: "Microsoft Pvt. Ltd.",
    role: "Front End Developer",
    location: "Bangalore",
    salary: "15 - 20 LPA",
    remote: false,
    duration: null,
    experience: "2 years",
    type: "Full Time",
    logo: "",
    applyBy: new Date(),
    techstack: ["React JS", "Node JS", "Mongo DB", "REST API"],
    description:
      'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum"',
    jd: [
      "Leverage the inbuilt React toolkit for creating frontend features",
      "Create data visualization tools, libraries, and reusable code for prospects",
      "Integrate designs and wireframes within the application code",
      "Monitor interaction of users and convert them into insightful information",
      "Write application interface code with JavaScript",
      "Enhance application performance with constant monitoring",
      "Translate wireframes and designs into good quality code",
      "Optimize components to work seamlessly across different browsers and devices",
      "Good understanding of CSS libraries, GIT, Sigma, Adobe XD etc.",
      "Proper user information authentication",
      "Develop responsive web-based UI",
    ],
  },
  {
    id: "J2",
    name: "Microsoft Pvt. Ltd.",
    role: "Front End Intern",
    location: "Bangalore",
    salary: "35K - 45K Per Month",
    remote: false,
    duration: "6 Months",
    experience: null,
    type: "Internship",
    logo: "",
    applyBy: new Date(),
    techstack: ["React JS", "Node JS"],
    description:
      'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum"',
    jd: [
      "experience in software development using modern languages (NodeJS, Angular, React, etc)",
      "Thorough understanding of Node.JS and its core principles",
      "Own code quality and experience in writing extensive unit tests",
      "Familiarity with modern front-end build pipelines and tools",
      "Proven ability to learn and adapt to new technologies and frameworks quickly",
    ],
  },
  {
    id: "J3",
    name: "Microsoft Pvt. Ltd.",
    role: "Part Time Developer",
    location: "Bangalore",
    salary: "1L - 1.25L Per Month",
    remote: true,
    duration: "6 Months",
    experience: "4 years",
    type: "Freelancing",
    logo: "",
    applyBy: new Date(),
    techstack: ["Python", "Jango"],
    description:
      'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum"',
    jd: [
      "experience in full stack web development",
      "experience in React JS",
      "experience in Python and Django",
      "experience in Django REST Framework and Django ORM",
      "Working knowledge on HTML, Javascript, CSS",
      "Should have knowledge of Component Design Approach",
      "Should have experience in SQL (experience in PostgreSQL would be an advantage)",
      "experience in AWS services",
    ],
  },
];

export const allApplicants = [
  {
    id: "J1",
    name: "Microsoft Pvt. Ltd.",
    role: "Front End Developer",
    location: "Bangalore",
    salary: "15 - 20 LPA",
    remote: false,
    duration: null,
    experience: "2 years",
    type: "Full Time",
    logo: "",
    applyBy: new Date(),
    techstack: ["React JS", "Node JS", "Mongo DB", "REST API"],
    candidateName: "Carry Smith",
    profileImg:
      "https://res.cloudinary.com/dgwzpbj4k/image/upload/v1650457646/baatchit/boy_urhxrp.png",
    email: "carrysmith@gmail.com",
    phNumber: "8733446273",
    resumeLink:
      "https://writing.colostate.edu/guides/documents/resume/functionalsample.pdf",
  },
  {
    id: "J2",
    name: "Microsoft Pvt. Ltd.",
    role: "Front End Intern",
    location: "Bangalore",
    salary: "35K - 45K Per Month",
    remote: false,
    duration: "6 Months",
    experience: null,
    type: "Internship",
    logo: "",
    applyBy: new Date(),
    techstack: ["React JS", "Node JS"],
    candidateName: "Carry Smith",
    profileImg:
      "https://res.cloudinary.com/dgwzpbj4k/image/upload/v1650457646/baatchit/boy_urhxrp.png",
    email: "carrysmith@gmail.com",
    phNumber: "8733446273",
    resumeLink:
      "https://writing.colostate.edu/guides/documents/resume/functionalsample.pdf",
  },
  {
    id: "J3",
    name: "Microsoft Pvt. Ltd.",
    role: "Part Time Developer",
    location: "Bangalore",
    salary: "1L - 1.25L Per Month",
    remote: true,
    duration: "6 Months",
    experience: "4 years",
    type: "Freelancing",
    logo: "",
    applyBy: new Date(),
    techstack: ["Python", "Jango"],
    candidateName: "Carry Smith",
    profileImg:
      "https://res.cloudinary.com/dgwzpbj4k/image/upload/v1650457646/baatchit/boy_urhxrp.png",
    email: "carrysmith@gmail.com",
    phNumber: "8733446273",
    resumeLink:
      "https://writing.colostate.edu/guides/documents/resume/functionalsample.pdf",
  },
];
